name: Test client
on:
  pull_request:
    branches:
      - main

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Run tests
      run: |
        docker build -t rajashekar435/client-test -f ./client/Dockerfile.dev ./client
        docker run -e CI=true rajashekar435/client-test npm run test -- --coverage