name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Configure Docker
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Run tests
      run: |
        docker build -t rajashekar435/client-test -f ./client/Dockerfile.dev ./client
        docker run -e CI=true rajashekar435/client-test npm run test -- --coverage

    - name: Build and push Docker images
      run: |
        docker build -t rajashekar435/multi-client:latest -t rajashekar435/multi-client:${{ github.sha }} -f ./client/Dockerfile ./client
        docker build -t rajashekar435/multi-server:latest -t rajashekar435/multi-server:${{ github.sha }} -f ./server/Dockerfile ./server
        docker build -t rajashekar435/multi-worker:latest -t rajashekar435/multi-worker:${{ github.sha }} -f ./worker/Dockerfile ./worker
        docker push rajashekar435/multi-client:latest
        docker push rajashekar435/multi-server:latest
        docker push rajashekar435/multi-worker:latest
        docker push rajashekar435/multi-client:${{ github.sha }}
        docker push rajashekar435/multi-server:${{ github.sha }}
        docker push rajashekar435/multi-worker:${{ github.sha }}

    - name: Set up kubectl
      run: gcloud container clusters get-credentials multik8s-cluster --zone us-central1-a
    
    - name: Apply Kubernetes files
      run: |
        kubectl apply -f k8s
        kubectl set image deployments/server-deployment server=rajashekar435/multi-server:${{ github.sha }}
        kubectl set image deployments/client-deployment client=rajashekar435/multi-client:${{ github.sha }}
        kubectl set image deployments/worker-deployment worker=rajashekar435/multi-worker:${{ github.sha }}
